export const primitiveColors = {
  neutral: [
    { name: "Neutral 0", hex: "#ffffff", class: "bg-neutral-0" },
    { name: "Neutral 25", hex: "#f6f6f8", class: "bg-neutral-25" },
    { name: "Neutral 50", hex: "#eff0f3", class: "bg-neutral-50" },
    { name: "Neutral 75", hex: "#e1e2e5", class: "bg-neutral-75" },
    { name: "Neutral 100", hex: "#cfd1d5", class: "bg-neutral-100" },
    { name: "Neutral 200", hex: "#a6aab1", class: "bg-neutral-200" },
    { name: "Neutral 300", hex: "#828995", class: "bg-neutral-300" },
    { name: "Neutral 400", hex: "#697280", class: "bg-neutral-400" },
    { name: "Neutral 500", hex: "#616b7a", class: "bg-neutral-500" },
    { name: "Neutral 600", hex: "#556070", class: "bg-neutral-600" },
    { name: "Neutral 700", hex: "#424f60", class: "bg-neutral-700" },
    { name: "Neutral 750", hex: "#2c3d52", class: "bg-neutral-750" },
    { name: "Neutral 800", hex: "#1e3145", class: "bg-neutral-800" },
    { name: "Neutral 850", hex: "#12283d", class: "bg-neutral-850" },
    { name: "Neutral 900", hex: "#081f33", class: "bg-neutral-900" },
    { name: "Neutral 1000", hex: "#031320", class: "bg-neutral-1000" },
  ],
  red: [
    { name: "Red 25", hex: "#fff6f7", class: "bg-red-25" },
    { name: "Red 50", hex: "#fdeced", class: "bg-red-50" },
    { name: "Red 100", hex: "#fadbdb", class: "bg-red-100" },
    { name: "Red 150", hex: "#f7c9cb", class: "bg-red-150" },
    { name: "Red 200", hex: "#f5b6b9", class: "bg-red-200" },
    { name: "Red 250", hex: "#f3a4a8", class: "bg-red-250" },
    { name: "Red 300", hex: "#f29095", class: "bg-red-300" },
    { name: "Red 350", hex: "#f07981", class: "bg-red-350" },
    { name: "Red 400", hex: "#ef626d", class: "bg-red-400" },
    { name: "Red 450", hex: "#ef4355", class: "bg-red-450" },
    { name: "Red 500", hex: "#e22a42", class: "bg-red-500" },
    { name: "Red 550", hex: "#ce1a35", class: "bg-red-550" },
    { name: "Red 600", hex: "#c31230", class: "bg-red-600" },
    { name: "Red 650", hex: "#a50e27", class: "bg-red-650" },
    { name: "Red 700", hex: "#910620", class: "bg-red-700" },
    { name: "Red 750", hex: "#7c031a", class: "bg-red-750" },
    { name: "Red 800", hex: "#650715", class: "bg-red-800" },
    { name: "Red 850", hex: "#52030f", class: "bg-red-850" },
    { name: "Red 900", hex: "#400108", class: "bg-red-900" },
    { name: "Red 950", hex: "#2a0305", class: "bg-red-950" },
  ],
  orange: [
    { name: "Orange 25", hex: "#fef8e4", class: "bg-orange-25" },
    { name: "Orange 50", hex: "#fef4d3", class: "bg-orange-50" },
    { name: "Orange 100", hex: "#ffddb8", class: "bg-orange-100" },
    { name: "Orange 150", hex: "#ffc9a4", class: "bg-orange-150" },
    { name: "Orange 200", hex: "#ffb68f", class: "bg-orange-200" },
    { name: "Orange 250", hex: "#ffa279", class: "bg-orange-250" },
    { name: "Orange 300", hex: "#fc8d64", class: "bg-orange-300" },
    { name: "Orange 350", hex: "#f8784d", class: "bg-orange-350" },
    { name: "Orange 400", hex: "#f15729", class: "bg-orange-400" },
    { name: "Orange 450", hex: "#e65125", class: "bg-orange-450" },
    { name: "Orange 500", hex: "#cf4921", class: "bg-orange-500" },
    { name: "Orange 550", hex: "#bb421f", class: "bg-orange-550" },
    { name: "Orange 600", hex: "#a73918", class: "bg-orange-600" },
    { name: "Orange 650", hex: "#923215", class: "bg-orange-650" },
    { name: "Orange 700", hex: "#80290f", class: "bg-orange-700" },
    { name: "Orange 750", hex: "#6c230d", class: "bg-orange-750" },
    { name: "Orange 800", hex: "#5b1a07", class: "bg-orange-800" },
    { name: "Orange 850", hex: "#481405", class: "bg-orange-850" },
    { name: "Orange 900", hex: "#370e06", class: "bg-orange-900" },
    { name: "Orange 950", hex: "#270600", class: "bg-orange-950" },
  ],
  yellow: [
    { name: "Yellow 25", hex: "#fdf7ce", class: "bg-yellow-25" },
    { name: "Yellow 50", hex: "#fef1b7", class: "bg-yellow-50" },
    { name: "Yellow 100", hex: "#f9e280", class: "bg-yellow-100" },
    { name: "Yellow 150", hex: "#f5d000", class: "bg-yellow-150" },
    { name: "Yellow 200", hex: "#e8c403", class: "bg-yellow-200" },
    { name: "Yellow 250", hex: "#d9b600", class: "bg-yellow-250" },
    { name: "Yellow 300", hex: "#caa809", class: "bg-yellow-300" },
    { name: "Yellow 350", hex: "#bc9b00", class: "bg-yellow-350" },
    { name: "Yellow 400", hex: "#ad8e00", class: "bg-yellow-400" },
    { name: "Yellow 450", hex: "#9e8102", class: "bg-yellow-450" },
    { name: "Yellow 500", hex: "#907300", class: "bg-yellow-500" },
    { name: "Yellow 550", hex: "#826700", class: "bg-yellow-550" },
    { name: "Yellow 600", hex: "#755b00", class: "bg-yellow-600" },
    { name: "Yellow 650", hex: "#684f02", class: "bg-yellow-650" },
    { name: "Yellow 700", hex: "#5b4301", class: "bg-yellow-700" },
    { name: "Yellow 750", hex: "#4e3701", class: "bg-yellow-750" },
    { name: "Yellow 800", hex: "#422d00", class: "bg-yellow-800" },
    { name: "Yellow 850", hex: "#342300", class: "bg-yellow-850" },
    { name: "Yellow 900", hex: "#271900", class: "bg-yellow-900" },
    { name: "Yellow 950", hex: "#1a0f00", class: "bg-yellow-950" },
  ],
  green: [
    { name: "Green 25", hex: "#f0fbf3", class: "bg-green-25" },
    { name: "Green 50", hex: "#e6f7ea", class: "bg-green-50" },
    { name: "Green 100", hex: "#cde9d3", class: "bg-green-100" },
    { name: "Green 150", hex: "#baddc1", class: "bg-green-150" },
    { name: "Green 200", hex: "#a7d1b0", class: "bg-green-200" },
    { name: "Green 250", hex: "#92c49d", class: "bg-green-250" },
    { name: "Green 300", hex: "#7eb88c", class: "bg-green-300" },
    { name: "Green 350", hex: "#69ac7a", class: "bg-green-350" },
    { name: "Green 400", hex: "#52a167", class: "bg-green-400" },
    { name: "Green 450", hex: "#3a9556", class: "bg-green-450" },
    { name: "Green 500", hex: "#198844", class: "bg-green-500" },
    { name: "Green 550", hex: "#0f7b3d", class: "bg-green-550" },
    { name: "Green 600", hex: "#116d35", class: "bg-green-600" },
    { name: "Green 650", hex: "#0e5f2d", class: "bg-green-650" },
    { name: "Green 700", hex: "#0d5227", class: "bg-green-700" },
    { name: "Green 750", hex: "#084520", class: "bg-green-750" },
    { name: "Green 800", hex: "#033918", class: "bg-green-800" },
    { name: "Green 850", hex: "#032d13", class: "bg-green-850" },
    { name: "Green 900", hex: "#00210a", class: "bg-green-900" },
    { name: "Green 950", hex: "#011506", class: "bg-green-950" },
  ],
  mint: [
    { name: "Mint 25", hex: "#e3fef1", class: "bg-mint-25" },
    { name: "Mint 50", hex: "#c6fce4", class: "bg-mint-50" },
    { name: "Mint 100", hex: "#a9f2d3", class: "bg-mint-100" },
    { name: "Mint 150", hex: "#82e8bf", class: "bg-mint-150" },
    { name: "Mint 200", hex: "#50dcaa", class: "bg-mint-200" },
    { name: "Mint 250", hex: "#49cea0", class: "bg-mint-250" },
    { name: "Mint 300", hex: "#44bf93", class: "bg-mint-300" },
    { name: "Mint 350", hex: "#41b088", class: "bg-mint-350" },
    { name: "Mint 400", hex: "#38a27c", class: "bg-mint-400" },
    { name: "Mint 450", hex: "#349470", class: "bg-mint-450" },
    { name: "Mint 500", hex: "#2a8565", class: "bg-mint-500" },
    { name: "Mint 550", hex: "#28785b", class: "bg-mint-550" },
    { name: "Mint 600", hex: "#246a51", class: "bg-mint-600" },
    { name: "Mint 650", hex: "#1c5d46", class: "bg-mint-650" },
    { name: "Mint 700", hex: "#19503c", class: "bg-mint-700" },
    { name: "Mint 750", hex: "#144332", class: "bg-mint-750" },
    { name: "Mint 800", hex: "#0d3728", class: "bg-mint-800" },
    { name: "Mint 850", hex: "#0a2b1f", class: "bg-mint-850" },
    { name: "Mint 900", hex: "#042015", class: "bg-mint-900" },
    { name: "Mint 950", hex: "#02140d", class: "bg-mint-950" },
  ],
  turquoise: [
    { name: "Turquoise 25", hex: "#e4fafe", class: "bg-turquoise-25" },
    { name: "Turquoise 50", hex: "#cef7ff", class: "bg-turquoise-50" },
    { name: "Turquoise 100", hex: "#a4eefe", class: "bg-turquoise-100" },
    { name: "Turquoise 150", hex: "#73e4fc", class: "bg-turquoise-150" },
    { name: "Turquoise 200", hex: "#3ddcfa", class: "bg-turquoise-200" },
    { name: "Turquoise 250", hex: "#35c9e4", class: "bg-turquoise-250" },
    { name: "Turquoise 300", hex: "#34bad4", class: "bg-turquoise-300" },
    { name: "Turquoise 350", hex: "#2bacc4", class: "bg-turquoise-350" },
    { name: "Turquoise 400", hex: "#299eb4", class: "bg-turquoise-400" },
    { name: "Turquoise 450", hex: "#2690a4", class: "bg-turquoise-450" },
    { name: "Turquoise 500", hex: "#1f8194", class: "bg-turquoise-500" },
    { name: "Turquoise 550", hex: "#207484", class: "bg-turquoise-550" },
    { name: "Turquoise 600", hex: "#176777", class: "bg-turquoise-600" },
    { name: "Turquoise 650", hex: "#155a68", class: "bg-turquoise-650" },
    { name: "Turquoise 700", hex: "#0e4e5a", class: "bg-turquoise-700" },
    { name: "Turquoise 750", hex: "#0d414b", class: "bg-turquoise-750" },
    { name: "Turquoise 800", hex: "#0a353e", class: "bg-turquoise-800" },
    { name: "Turquoise 850", hex: "#052a32", class: "bg-turquoise-850" },
    { name: "Turquoise 900", hex: "#051f25", class: "bg-turquoise-900" },
    { name: "Turquoise 950", hex: "#001419", class: "bg-turquoise-950" },
  ],
  blue: [
    { name: "Blue 25", hex: "#eff9ff", class: "bg-blue-25" },
    { name: "Blue 50", hex: "#e7f6ff", class: "bg-blue-50" },
    { name: "Blue 75", hex: "#dbefff", class: "bg-blue-75" },
    { name: "Blue 100", hex: "#cbe5ff", class: "bg-blue-100" },
    { name: "Blue 150", hex: "#b4d8ff", class: "bg-blue-150" },
    { name: "Blue 200", hex: "#9ecaff", class: "bg-blue-200" },
    { name: "Blue 250", hex: "#84b7ff", class: "bg-blue-250" },
    { name: "Blue 300", hex: "#71adfc", class: "bg-blue-300" },
    { name: "Blue 350", hex: "#5b9ff9", class: "bg-blue-350" },
    { name: "Blue 400", hex: "#4e91f1", class: "bg-blue-400" },
    { name: "Blue 450", hex: "#3982ed", class: "bg-blue-450" },
    { name: "Blue 500", hex: "#2e73e1", class: "bg-blue-500" },
    { name: "Blue 550", hex: "#1f68dd", class: "bg-blue-550" },
    { name: "Blue 600", hex: "#1c5dc5", class: "bg-blue-600" },
    { name: "Blue 650", hex: "#1950aa", class: "bg-blue-650" },
    { name: "Blue 700", hex: "#184390", class: "bg-blue-700" },
    { name: "Blue 750", hex: "#12387b", class: "bg-blue-750" },
    { name: "Blue 800", hex: "#0b2e67", class: "bg-blue-800" },
    { name: "Blue 850", hex: "#072857", class: "bg-blue-850" },
    { name: "Blue 900", hex: "#032142", class: "bg-blue-900" },
  ],
  violet: [
    { name: "Violet 25", hex: "#f7f7fe", class: "bg-violet-25" },
    { name: "Violet 50", hex: "#f2f2fd", class: "bg-violet-50" },
    { name: "Violet 100", hex: "#dee1fd", class: "bg-violet-100" },
    { name: "Violet 150", hex: "#cdd2fb", class: "bg-violet-150" },
    { name: "Violet 200", hex: "#bbc3f9", class: "bg-violet-200" },
    { name: "Violet 250", hex: "#abb4f9", class: "bg-violet-250" },
    { name: "Violet 300", hex: "#9ca6f6", class: "bg-violet-300" },
    { name: "Violet 350", hex: "#8c97f3", class: "bg-violet-350" },
    { name: "Violet 400", hex: "#7e87ef", class: "bg-violet-400" },
    { name: "Violet 450", hex: "#7078eb", class: "bg-violet-450" },
    { name: "Violet 500", hex: "#6268e7", class: "bg-violet-500" },
    { name: "Violet 550", hex: "#5a5ae6", class: "bg-violet-550" },
    { name: "Violet 600", hex: "#4e4ec8", class: "bg-violet-600" },
    { name: "Violet 650", hex: "#4343b2", class: "bg-violet-650" },
    { name: "Violet 700", hex: "#393a9c", class: "bg-violet-700" },
    { name: "Violet 750", hex: "#313083", class: "bg-violet-750" },
    { name: "Violet 800", hex: "#27276f", class: "bg-violet-800" },
    { name: "Violet 850", hex: "#1f1e57", class: "bg-violet-850" },
    { name: "Violet 900", hex: "#151544", class: "bg-violet-900" },
    { name: "Violet 950", hex: "#0c0b31", class: "bg-violet-950" },
  ],
  grape: [
    { name: "Grape 25", hex: "#fbf2fd", class: "bg-grape-25" },
    { name: "Grape 50", hex: "#fbecfd", class: "bg-grape-50" },
    { name: "Grape 100", hex: "#fad7fd", class: "bg-grape-100" },
    { name: "Grape 150", hex: "#f7c4fb", class: "bg-grape-150" },
    { name: "Grape 200", hex: "#f5aefb", class: "bg-grape-200" },
    { name: "Grape 250", hex: "#f09af7", class: "bg-grape-250" },
    { name: "Grape 300", hex: "#eb7af5", class: "bg-grape-300" },
    { name: "Grape 350", hex: "#df74e8", class: "bg-grape-350" },
    { name: "Grape 400", hex: "#cd6ad6", class: "bg-grape-400" },
    { name: "Grape 450", hex: "#bb60c3", class: "bg-grape-450" },
    { name: "Grape 500", hex: "#aa55b2", class: "bg-grape-500" },
    { name: "Grape 550", hex: "#994da0", class: "bg-grape-550" },
    { name: "Grape 600", hex: "#87448d", class: "bg-grape-600" },
    { name: "Grape 650", hex: "#773a7d", class: "bg-grape-650" },
    { name: "Grape 700", hex: "#67326b", class: "bg-grape-700" },
    { name: "Grape 750", hex: "#572a5b", class: "bg-grape-750" },
    { name: "Grape 800", hex: "#48214c", class: "bg-grape-800" },
    { name: "Grape 850", hex: "#39193c", class: "bg-grape-850" },
    { name: "Grape 900", hex: "#2c112f", class: "bg-grape-900" },
    { name: "Grape 950", hex: "#1d091f", class: "bg-grape-950" },
  ],
  pink: [
    { name: "Pink 25", hex: "#fff0fc", class: "bg-pink-25" },
    { name: "Pink 50", hex: "#ffebf8", class: "bg-pink-50" },
    { name: "Pink 100", hex: "#ffd8e9", class: "bg-pink-100" },
    { name: "Pink 150", hex: "#fec5da", class: "bg-pink-150" },
    { name: "Pink 200", hex: "#feb0ca", class: "bg-pink-200" },
    { name: "Pink 250", hex: "#ff9bbc", class: "bg-pink-250" },
    { name: "Pink 300", hex: "#ff84ac", class: "bg-pink-300" },
    { name: "Pink 350", hex: "#f6729b", class: "bg-pink-350" },
    { name: "Pink 400", hex: "#ee5f89", class: "bg-pink-400" },
    { name: "Pink 450", hex: "#e44b79", class: "bg-pink-450" },
    { name: "Pink 500", hex: "#da2f66", class: "bg-pink-500" },
    { name: "Pink 550", hex: "#c52d5d", class: "bg-pink-550" },
    { name: "Pink 600", hex: "#af2953", class: "bg-pink-600" },
    { name: "Pink 650", hex: "#96274a", class: "bg-pink-650" },
    { name: "Pink 700", hex: "#812340", class: "bg-pink-700" },
    { name: "Pink 750", hex: "#6c1e37", class: "bg-pink-750" },
    { name: "Pink 800", hex: "#551b2d", class: "bg-pink-800" },
    { name: "Pink 850", hex: "#451524", class: "bg-pink-850" },
    { name: "Pink 900", hex: "#340e1a", class: "bg-pink-900" },
    { name: "Pink 950", hex: "#23070f", class: "bg-pink-950" },
  ],
  alphaDarken: [
    {
      name: "Alpha Darken 5",
      hex: "rgba(0, 0, 0, 0.05)",
      class: "bg-alpha-darken-5",
    },
    {
      name: "Alpha Darken 10",
      hex: "rgba(0, 0, 0, 0.1)",
      class: "bg-alpha-darken-10",
    },
    {
      name: "Alpha Darken 20",
      hex: "rgba(0, 0, 0, 0.2)",
      class: "bg-alpha-darken-20",
    },
    {
      name: "Alpha Darken 30",
      hex: "rgba(0, 0, 0, 0.3)",
      class: "bg-alpha-darken-30",
    },
    {
      name: "Alpha Darken 40",
      hex: "rgba(0, 0, 0, 0.4)",
      class: "bg-alpha-darken-40",
    },
    {
      name: "Alpha Darken 50",
      hex: "rgba(0, 0, 0, 0.5)",
      class: "bg-alpha-darken-50",
    },
    {
      name: "Alpha Darken 60",
      hex: "rgba(0, 0, 0, 0.6)",
      class: "bg-alpha-darken-60",
    },
    {
      name: "Alpha Darken 70",
      hex: "rgba(0, 0, 0, 0.7)",
      class: "bg-alpha-darken-70",
    },
    {
      name: "Alpha Darken 80",
      hex: "rgba(0, 0, 0, 0.8)",
      class: "bg-alpha-darken-80",
    },
    {
      name: "Alpha Darken 90",
      hex: "rgba(0, 0, 0, 0.9)",
      class: "bg-alpha-darken-90",
    },
    {
      name: "Alpha Darken 95",
      hex: "rgba(0, 0, 0, 0.95)",
      class: "bg-alpha-darken-95",
    },
  ],
  alphaLighten: [
    {
      name: "Alpha Lighten 5",
      hex: "rgba(255, 255, 255, 0.05)",
      class: "bg-alpha-lighten-5",
    },
    {
      name: "Alpha Lighten 10",
      hex: "rgba(255, 255, 255, 0.1)",
      class: "bg-alpha-lighten-10",
    },
    {
      name: "Alpha Lighten 20",
      hex: "rgba(255, 255, 255, 0.2)",
      class: "bg-alpha-lighten-20",
    },
    {
      name: "Alpha Lighten 30",
      hex: "rgba(255, 255, 255, 0.3)",
      class: "bg-alpha-lighten-30",
    },
    {
      name: "Alpha Lighten 40",
      hex: "rgba(255, 255, 255, 0.4)",
      class: "bg-alpha-lighten-40",
    },
    {
      name: "Alpha Lighten 50",
      hex: "rgba(255, 255, 255, 0.5)",
      class: "bg-alpha-lighten-50",
    },
    {
      name: "Alpha Lighten 60",
      hex: "rgba(255, 255, 255, 0.6)",
      class: "bg-alpha-lighten-60",
    },
    {
      name: "Alpha Lighten 70",
      hex: "rgba(255, 255, 255, 0.7)",
      class: "bg-alpha-lighten-70",
    },
    {
      name: "Alpha Lighten 80",
      hex: "rgba(255, 255, 255, 0.8)",
      class: "bg-alpha-lighten-80",
    },
    {
      name: "Alpha Lighten 90",
      hex: "rgba(255, 255, 255, 0.9)",
      class: "bg-alpha-lighten-90",
    },
    {
      name: "Alpha Lighten 95",
      hex: "rgba(255, 255, 255, 0.95)",
      class: "bg-alpha-lighten-95",
    },
  ],
};

export type PrimitiveColor =
  (typeof primitiveColors)[keyof typeof primitiveColors][number];

export const semanticColors = {
  action: [
    {
      name: "Action Default",
      hex: { light: "#1f68dd", dark: "#71adfc" },
      class: "bg-action-default",
      description: "Primary action color",
    },
    {
      name: "Action Hover",
      hex: { light: "#184390", dark: "#cbe5ff" },
      class: "bg-action-hover",
      description: "Action on hover",
    },
    {
      name: "Action Active",
      hex: { light: "#1c5dc5", dark: "#9ecaff" },
      class: "bg-action-active",
      description: "Action pressed/active state",
    },
    {
      name: "Action Focus",
      hex: { light: "#1c5dc5", dark: "#1c5dc5" },
      class: "bg-action-focus",
      description: "Focus ring color",
    },
    {
      name: "Action Disabled Default",
      hex: { light: "#828995", dark: "#828995" },
      class: "bg-action-disabled-default",
      description: "Disabled action color",
    },
    {
      name: "Action Disabled Inverse",
      hex: { light: "#e1e2e5", dark: "#e1e2e5" },
      class: "bg-action-disabled-inverse",
      description: "Disabled action on dark background",
    },
    {
      name: "Action Secondary Hover",
      hex: { light: "#eff0f3", dark: "#eff0f3" },
      class: "bg-action-secondary-hover",
      description: "Secondary action hover",
    },
    {
      name: "Action Secondary Active",
      hex: { light: "#e1e2e5", dark: "#e1e2e5" },
      class: "bg-action-secondary-active",
      description: "Secondary action active",
    },
    {
      name: "Action Negative Hover",
      hex: { light: "#fdeced", dark: "#fadbdb" },
      class: "bg-action-negative-hover",
      description: "Negative action hover",
    },
    {
      name: "Action Negative Active",
      hex: { light: "#f7c9cb", dark: "#f7c9cb" },
      class: "bg-action-negative-active",
      description: "Negative action active",
    },
    {
      name: "Action Inverse Hover",
      hex: { light: "#1e3145", dark: "#1e3145" },
      class: "bg-action-inverse-hover",
      description: "Inverse action hover",
    },
    {
      name: "Action Inverse Active",
      hex: { light: "#424f60", dark: "#424f60" },
      class: "bg-action-inverse-active",
      description: "Inverse action active",
    },
  ],
  text: [
    {
      name: "Text Default",
      hex: { light: "#1e3145", dark: "#ffffff" },
      class: "bg-text-default",
      description: "Primary text color",
    },
    {
      name: "Text Faint",
      hex: { light: "#616b7a", dark: "#cfd1d5" },
      class: "bg-text-faint",
      description: "Faint text color",
    },
    {
      name: "Text Muted",
      hex: { light: "#424f60", dark: "#e1e2e5" },
      class: "bg-text-muted",
      description: "Muted text color",
    },
    {
      name: "Text Inverse",
      hex: { light: "#ffffff", dark: "#081f33" },
      class: "bg-text-inverse",
      description: "Text on dark background",
    },
  ],
  icon: [
    {
      name: "Icon Default",
      hex: { light: "#1e3145", dark: "#ffffff" },
      class: "bg-icon-default",
      description: "Default icon color",
    },
    {
      name: "Icon Muted",
      hex: { light: "#424f60", dark: "#eff0f3" },
      class: "bg-icon-muted",
      description: "Muted icon color",
    },
    {
      name: "Icon Faint",
      hex: { light: "#616b7a", dark: "#cfd1d5" },
      class: "bg-icon-faint",
      description: "Faint icon color",
    },
    {
      name: "Icon Inverse",
      hex: { light: "#ffffff", dark: "#081f33" },
      class: "bg-icon-inverse",
      description: "Icon on dark background",
    },
  ],
  background: [
    {
      name: "Background Primary",
      hex: { light: "#ffffff", dark: "#1e3145" },
      class: "bg-background-primary",
      description: "Main background",
    },
    {
      name: "Background Secondary",
      hex: { light: "#f6f6f8", dark: "#081f33" },
      class: "bg-background-secondary",
      description: "Secondary background",
    },
    {
      name: "Background Tertiary",
      hex: { light: "#eff0f3", dark: "#1e3145" },
      class: "bg-background-tertiary",
      description: "Tertiary background",
    },
    {
      name: "Background Quaternary",
      hex: { light: "#e1e2e5", dark: "#424f60" },
      class: "bg-background-quaternary",
      description: "Quaternary background",
    },
    {
      name: "Background Inverse Primary",
      hex: { light: "#081f33", dark: "#ffffff" },
      class: "bg-background-inverse-primary",
      description: "Primary dark background",
    },
    {
      name: "Background Inverse Secondary",
      hex: { light: "#1e3145", dark: "#f6f6f8" },
      class: "bg-background-inverse-secondary",
      description: "Secondary dark background",
    },
    {
      name: "Background Inverse Tertiary",
      hex: { light: "#424f60", dark: "#eff0f3" },
      class: "bg-background-inverse-tertiary",
      description: "Tertiary dark background",
    },
    {
      name: "Background Inverse Quaternary",
      hex: { light: "#556070", dark: "#e1e2e5" },
      class: "bg-background-inverse-quaternary",
      description: "Quaternary dark background",
    },
  ],
  sentiment: [
    {
      name: "Positive Foreground",
      hex: { light: "#0f7b3d", dark: "#7eb88c" },
      class: "bg-sentiment-positive-foreground",
      description: "Positive sentiment text",
    },
    {
      name: "Positive Background",
      hex: { light: "#f0fbf3", dark: "#033918" },
      class: "bg-sentiment-positive-background",
      description: "Positive sentiment background",
    },
    {
      name: "Negative Foreground",
      hex: { light: "#c31230", dark: "#ef626d" },
      class: "bg-sentiment-negative-foreground",
      description: "Negative sentiment text",
    },
    {
      name: "Negative Background",
      hex: { light: "#fff6f7", dark: "#650715" },
      class: "bg-sentiment-negative-background",
      description: "Negative sentiment background",
    },
    {
      name: "Neutral Foreground",
      hex: { light: "#616b7a", dark: "#828995" },
      class: "bg-sentiment-neutral-foreground",
      description: "Neutral sentiment text",
    },
    {
      name: "Neutral Background",
      hex: { light: "#f6f6f8", dark: "#1e3145" },
      class: "bg-sentiment-neutral-background",
      description: "Neutral sentiment background",
    },
    {
      name: "Warning Foreground",
      hex: { light: "#bb421f", dark: "#fc8d64" },
      class: "bg-sentiment-warning-foreground",
      description: "Warning sentiment text",
    },
    {
      name: "Warning Background",
      hex: { light: "#fef8e4", dark: "#5b1a07" },
      class: "bg-sentiment-warning-background",
      description: "Warning sentiment background",
    },
    {
      name: "Inform Foreground",
      hex: { light: "#1f68dd", dark: "#5b9ff9" },
      class: "bg-sentiment-inform-foreground",
      description: "Informational sentiment text",
    },
    {
      name: "Inform Background",
      hex: { light: "#eff9ff", dark: "#0b2e67" },
      class: "bg-sentiment-inform-background",
      description: "Informational sentiment background",
    },
    {
      name: "Standard Foreground",
      hex: { light: "#cfd1d5", dark: "#ffffff" },
      class: "bg-sentiment-standard-foreground",
      description: "Standard sentiment text",
    },
    {
      name: "Standard Background",
      hex: { light: "#ffffff", dark: "#424f60" },
      class: "bg-sentiment-standard-background",
      description: "Standard sentiment background",
    },
  ],
  border: [
    {
      name: "Border Soft",
      hex: { light: "#e1e2e5", dark: "#616b7a" },
      class: "bg-border-soft",
      description: "Soft border color",
    },
    {
      name: "Border Subtle",
      hex: { light: "#cfd1d5", dark: "#081f33" },
      class: "bg-border-subtle",
      description: "Subtle border color",
    },
    {
      name: "Border Regular",
      hex: { light: "#a6aab1", dark: "#556070" },
      class: "bg-border-regular",
      description: "Regular border color",
    },
    {
      name: "Border Strong",
      hex: { light: "#828995", dark: "#616b7a" },
      class: "bg-border-strong",
      description: "Strong border color",
    },
  ],
  datavizMoney: [
    {
      name: "Money In Fill",
      hex: { light: "#3982ed", dark: "#4e91f1" },
      class: "bg-dataviz-money-in-fill",
      description: "Money in visualization fill",
    },
    {
      name: "Money In Stroke",
      hex: { light: "#3982ed", dark: "#4e91f1" },
      class: "bg-dataviz-money-in-stroke",
      description: "Money in visualization stroke",
    },
    {
      name: "Money Out Fill",
      hex: { light: "#b4d8ff", dark: "#9ecaff" },
      class: "bg-dataviz-money-out-fill",
      description: "Money out visualization fill",
    },
    {
      name: "Money Out Stroke",
      hex: { light: "#3982ed", dark: "#4e91f1" },
      class: "bg-dataviz-money-out-stroke",
      description: "Money out visualization stroke",
    },
  ],
  datavizNeutral: [
    {
      name: "Neutral Fill 01",
      hex: { light: "#e1e2e5", dark: "#556070" },
      class: "bg-dataviz-neutral-fill-01",
      description: "Neutral fill 01",
    },
    {
      name: "Neutral Fill 02",
      hex: { light: "#cfd1d5", dark: "#616b7a" },
      class: "bg-dataviz-neutral-fill-02",
      description: "Neutral fill 02",
    },
    {
      name: "Neutral Fill 03",
      hex: { light: "#a6aab1", dark: "#697280" },
      class: "bg-dataviz-neutral-fill-03",
      description: "Neutral fill 03",
    },
    {
      name: "Neutral Fill 04",
      hex: { light: "#828995", dark: "#828995" },
      class: "bg-dataviz-neutral-fill-04",
      description: "Neutral fill 04",
    },
    {
      name: "Neutral Fill 05",
      hex: { light: "#697280", dark: "#a6aab1" },
      class: "bg-dataviz-neutral-fill-05",
      description: "Neutral fill 05",
    },
    {
      name: "Neutral Fill 06",
      hex: { light: "#616b7a", dark: "#cfd1d5" },
      class: "bg-dataviz-neutral-fill-06",
      description: "Neutral fill 06",
    },
    {
      name: "Neutral Fill 07",
      hex: { light: "#556070", dark: "#e1e2e5" },
      class: "bg-dataviz-neutral-fill-07",
      description: "Neutral fill 07",
    },
    {
      name: "Neutral Fill 08",
      hex: { light: "#424f60", dark: "#eff0f3" },
      class: "bg-dataviz-neutral-fill-08",
      description: "Neutral fill 08",
    },
    {
      name: "Neutral Fill 09",
      hex: { light: "#1e3145", dark: "#f6f6f8" },
      class: "bg-dataviz-neutral-fill-09",
      description: "Neutral fill 09",
    },
    {
      name: "Neutral Fill 10",
      hex: { light: "#081f33", dark: "#ffffff" },
      class: "bg-dataviz-neutral-fill-10",
      description: "Neutral fill 10",
    },
    {
      name: "Neutral Border",
      hex: { light: "#828995", dark: "#697280" },
      class: "bg-dataviz-neutral-border",
      description: "Neutral border",
    },
    {
      name: "Neutral Primary",
      hex: { light: "#a6aab1", dark: "#828995" },
      class: "bg-dataviz-neutral-primary",
      description: "Neutral primary",
    },
    {
      name: "Neutral Secondary",
      hex: { light: "#1e3145", dark: "#e1e2e5" },
      class: "bg-dataviz-neutral-secondary",
      description: "Neutral secondary",
    },
  ],
  datavizTonal: [
    {
      name: "Tonal Fill 01",
      hex: { light: "#b4d8ff", dark: "#9ecaff" },
      class: "bg-dataviz-tonal-fill-01",
      description: "Tonal fill 01",
    },
    {
      name: "Tonal Fill 02",
      hex: { light: "#84b7ff", dark: "#71adfc" },
      class: "bg-dataviz-tonal-fill-02",
      description: "Tonal fill 02",
    },
    {
      name: "Tonal Fill 03",
      hex: { light: "#5b9ff9", dark: "#5b9ff9" },
      class: "bg-dataviz-tonal-fill-03",
      description: "Tonal fill 03",
    },
    {
      name: "Tonal Fill 04",
      hex: { light: "#3982ed", dark: "#4e91f1" },
      class: "bg-dataviz-tonal-fill-04",
      description: "Tonal fill 04",
    },
    {
      name: "Tonal Fill 05",
      hex: { light: "#1f68dd", dark: "#2e73e1" },
      class: "bg-dataviz-tonal-fill-05",
      description: "Tonal fill 05",
    },
    {
      name: "Tonal Fill 06",
      hex: { light: "#1c5dc5", dark: "#1f68dd" },
      class: "bg-dataviz-tonal-fill-06",
      description: "Tonal fill 06",
    },
    {
      name: "Tonal Fill 07",
      hex: { light: "#1950aa", dark: "#1c5dc5" },
      class: "bg-dataviz-tonal-fill-07",
      description: "Tonal fill 07",
    },
    {
      name: "Tonal Fill 08",
      hex: { light: "#184390", dark: "#1950aa" },
      class: "bg-dataviz-tonal-fill-08",
      description: "Tonal fill 08",
    },
    {
      name: "Tonal Fill 09",
      hex: { light: "#12387b", dark: "#184390" },
      class: "bg-dataviz-tonal-fill-09",
      description: "Tonal fill 09",
    },
    {
      name: "Tonal Fill 10",
      hex: { light: "#0b2e67", dark: "#12387b" },
      class: "bg-dataviz-tonal-fill-10",
      description: "Tonal fill 10",
    },
    {
      name: "Tonal Border",
      hex: { light: "#3982ed", dark: "#4e91f1" },
      class: "bg-dataviz-tonal-border",
      description: "Tonal border",
    },
    {
      name: "Tonal Primary",
      hex: { light: "#b4d8ff", dark: "#9ecaff" },
      class: "bg-dataviz-tonal-primary",
      description: "Tonal primary",
    },
    {
      name: "Tonal Secondary",
      hex: { light: "#3982ed", dark: "#4e91f1" },
      class: "bg-dataviz-tonal-secondary",
      description: "Tonal secondary",
    },
  ],
  datavizFramework: [
    {
      name: "Framework Negative Fill",
      hex: { light: "#c31230", dark: "#f29090" },
      class: "bg-dataviz-framework-negative-fill",
      description: "Framework negative fill",
    },
    {
      name: "Framework Negative Stroke",
      hex: { light: "#c31230", dark: "#f29090" },
      class: "bg-dataviz-framework-negative-stroke",
      description: "Framework negative stroke",
    },
    {
      name: "Framework Positive Fill",
      hex: { light: "#0f7b3d", dark: "#52a167" },
      class: "bg-dataviz-framework-positive-fill",
      description: "Framework positive fill",
    },
    {
      name: "Framework Positive Stroke",
      hex: { light: "#0f7b3d", dark: "#52a167" },
      class: "bg-dataviz-framework-positive-stroke",
      description: "Framework positive stroke",
    },
    {
      name: "Framework Keylines",
      hex: { light: "#e1e2e5", dark: "#616b7a" },
      class: "bg-dataviz-framework-keylines",
      description: "Framework keylines",
    },
    {
      name: "Framework Labels",
      hex: { light: "#616b7a", dark: "#a6aab1" },
      class: "bg-dataviz-framework-labels",
      description: "Framework labels",
    },
  ],
  shadow: [
    {
      name: "Shadow Default",
      hex: { light: "rgba(0, 0, 0, 0.2)", dark: "rgba(0, 0, 0, 0.2)" },
      class: "bg-shadow-default",
      description: "Default shadow",
    },
    {
      name: "Shadow Subtle",
      hex: { light: "rgba(0, 0, 0, 0.05)", dark: "rgba(0, 0, 0, 0.05)" },
      class: "bg-shadow-subtle",
      description: "Subtle shadow",
    },
  ],
  theme: [
    {
      name: "Theme SB Default",
      hex: { light: "#1f68dd", dark: "#1f68dd" },
      class: "bg-theme-default",
      description: "Theme SB default color",
    },
    {
      name: "Theme Active",
      hex: { light: "#184390", dark: "#184390" },
      class: "bg-theme-active",
      description: "Theme active color",
    },
    {
      name: "Theme Hover",
      hex: { light: "#1c5dc5", dark: "#1c5dc5" },
      class: "bg-theme-hover",
      description: "Theme hover color",
    },
    {
      name: "Theme Accent",
      hex: { light: "#e7f6ff", dark: "#e7f6ff" },
      class: "bg-theme-accent",
      description: "Theme SB accent color",
    },
    {
      name: "Theme Background",
      hex: { light: "#1f68dd", dark: "#1f68dd" },
      class: "bg-theme-background",
      description: "Theme background color",
    },
    {
      name: "Theme Secondary Default",
      hex: { light: "#1c5dc5", dark: "#1c5dc5" },
      class: "bg-theme-secondary-default",
      description: "Theme secondary default color",
    },
    {
      name: "Theme Secondary Active",
      hex: { light: "#184390", dark: "#184390" },
      class: "bg-theme-secondary-active",
      description: "Theme secondary active color",
    },
    {
      name: "Theme Secondary Hover",
      hex: { light: "#1950aa", dark: "#1950aa" },
      class: "bg-theme-secondary-hover",
      description: "Theme secondary hover color",
    },
  ],
  pairColors: [
    {
      name: "Pink Foreground",
      hex: { light: "#551b2d", dark: "#f3a4a8" },
      class: "bg-pair-pink-foreground",
      description: "Pink pair foreground",
    },
    {
      name: "Pink Background",
      hex: { light: "#ff9bbc", dark: "#551b2d" },
      class: "bg-pair-pink-background",
      description: "Pink pair background",
    },
    {
      name: "Grape Foreground",
      hex: { light: "#48214c", dark: "#eb7af5" },
      class: "bg-pair-grape-foreground",
      description: "Grape pair foreground",
    },
    {
      name: "Grape Background",
      hex: { light: "#f09af7", dark: "#48214c" },
      class: "bg-pair-grape-background",
      description: "Grape pair background",
    },
    {
      name: "Violet Foreground",
      hex: { light: "#27276f", dark: "#9ca6f6" },
      class: "bg-pair-violet-foreground",
      description: "Violet pair foreground",
    },
    {
      name: "Violet Background",
      hex: { light: "#abb4f9", dark: "#27276f" },
      class: "bg-pair-violet-background",
      description: "Violet pair background",
    },
    {
      name: "Blue Foreground",
      hex: { light: "#0b2e67", dark: "#84b7ff" },
      class: "bg-pair-blue-foreground",
      description: "Blue pair foreground",
    },
    {
      name: "Blue Background",
      hex: { light: "#84b7ff", dark: "#0b2e67" },
      class: "bg-pair-blue-background",
      description: "Blue pair background",
    },
    {
      name: "Turquoise Foreground",
      hex: { light: "#0a353e", dark: "#34bad4" },
      class: "bg-pair-turquoise-foreground",
      description: "Turquoise pair foreground",
    },
    {
      name: "Turquoise Background",
      hex: { light: "#3ddcfa", dark: "#0a353e" },
      class: "bg-pair-turquoise-background",
      description: "Turquoise pair background",
    },
    {
      name: "Mint Foreground",
      hex: { light: "#0d3728", dark: "#44bf93" },
      class: "bg-pair-mint-foreground",
      description: "Mint pair foreground",
    },
    {
      name: "Mint Background",
      hex: { light: "#50dcaa", dark: "#0d3728" },
      class: "bg-pair-mint-background",
      description: "Mint pair background",
    },
    {
      name: "Green Foreground",
      hex: { light: "#033918", dark: "#7eb88c" },
      class: "bg-pair-green-foreground",
      description: "Green pair foreground",
    },
    {
      name: "Green Background",
      hex: { light: "#92c49d", dark: "#033918" },
      class: "bg-pair-green-background",
      description: "Green pair background",
    },
    {
      name: "Yellow Foreground",
      hex: { light: "#422d00", dark: "#f5d000" },
      class: "bg-pair-yellow-foreground",
      description: "Yellow pair foreground",
    },
    {
      name: "Yellow Background",
      hex: { light: "#f9e282", dark: "#422d00" },
      class: "bg-pair-yellow-background",
      description: "Yellow pair background",
    },
    {
      name: "Orange Foreground",
      hex: { light: "#5b1a07", dark: "#fc8d64" },
      class: "bg-pair-orange-foreground",
      description: "Orange pair foreground",
    },
    {
      name: "Orange Background",
      hex: { light: "#ffb68f", dark: "#5b1a07" },
      class: "bg-pair-orange-background",
      description: "Orange pair background",
    },
    {
      name: "Red Foreground",
      hex: { light: "#650715", dark: "#f29095" },
      class: "bg-pair-red-foreground",
      description: "Red pair foreground",
    },
    {
      name: "Red Background",
      hex: { light: "#f3a4a8", dark: "#650715" },
      class: "bg-pair-red-background",
      description: "Red pair background",
    },
  ],
  mask: [
    {
      name: "Mask Default",
      hex: { light: "rgba(0, 0, 0, 0.7)", dark: "rgba(0, 0, 0, 0.7)" },
      class: "bg-mask-default",
      description: "Default mask color",
    },
  ],
  indicator: [
    {
      name: "Indicator Red",
      hex: { light: "#c31230", dark: "#f29090" },
      class: "bg-indicator-red",
      description: "Red indicator",
    },
    {
      name: "Indicator Orange",
      hex: { light: "#cf4921", dark: "#f15729" },
      class: "bg-indicator-orange",
      description: "Orange indicator",
    },
    {
      name: "Indicator Yellow",
      hex: { light: "#907300", dark: "#ad8e00" },
      class: "bg-indicator-yellow",
      description: "Yellow indicator",
    },
    {
      name: "Indicator Green",
      hex: { light: "#0f7b3d", dark: "#52a167" },
      class: "bg-indicator-green",
      description: "Green indicator",
    },
    {
      name: "Indicator Mint",
      hex: { light: "#2a8565", dark: "#38a27c" },
      class: "bg-indicator-mint",
      description: "Mint indicator",
    },
    {
      name: "Indicator Turquoise",
      hex: { light: "#1f8194", dark: "#299eb4" },
      class: "bg-indicator-turquoise",
      description: "Turquoise indicator",
    },
    {
      name: "Indicator Blue",
      hex: { light: "#2e73e1", dark: "#4e91f1" },
      class: "bg-indicator-blue",
      description: "Blue indicator",
    },
    {
      name: "Indicator Violet",
      hex: { light: "#6268e7", dark: "#7e87ef" },
      class: "bg-indicator-violet",
      description: "Violet indicator",
    },
    {
      name: "Indicator Grape",
      hex: { light: "#aa55b2", dark: "#cd6ad6" },
      class: "bg-indicator-grape",
      description: "Grape indicator",
    },
    {
      name: "Indicator Pink",
      hex: { light: "#da2f66", dark: "#ee5f89" },
      class: "bg-indicator-pink",
      description: "Pink indicator",
    },
    {
      name: "Indicator Gray",
      hex: { light: "#616b7a", dark: "#a6aab1" },
      class: "bg-indicator-gray",
      description: "Gray indicator",
    },
  ],
};

export type SemanticColor =
  (typeof semanticColors)[keyof typeof semanticColors][number];
